name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - master


jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install system packages
        run: |
          sudo apt-get update -qq && sudo apt-get install libvips-dev
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup
      - name: Run tests
        run: bin/rails test