name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - master


jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install system packages
        run: |
          sudo apt-get update -qq && sudo apt-get install libvips-dev
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.4.0
          cache: "yarn"
      - name: Install packages
        run: |
          yarn install --pure-lockfile
      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup
      - name: Run tests
        run: bin/rails test
      - name: Run system tests
        env:
          PARALLEL_WORKERS: 1
        run: bin/rails test:system
      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: $/tmp/screenshots
          if-no-files-found: ignore